# Generated by Django 4.2.4 on 2023-08-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, verbose_name='telegram file id')),
                ('filename', models.CharField(max_length=255, verbose_name='file name')),
            ],
        ),
    ]
