# Generated by Django 4.2.4 on 2023-08-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaids',
            name='file_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='telegram file id'),
        ),
        migrations.AlterField(
            model_name='mediaids',
            name='filename',
            field=models.CharField(max_length=255, unique=True, verbose_name='file name'),
        ),
    ]
